name: Run C++ Script on GitHub Cloud

on:
  push:
    branches: [ "main" ]

jobs:
  run-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Build and execute C++ application
        run: |
          cmake -B build
          cmake --build build
          ./build/firmware_app   # Runs directly on GitHub's cloud server!
